# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'hack59-app' do

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'
pod 'MBProgressHUD', '~> 0.8'

pod "AFNetworking", "~> 2.0"

end

